{% set version = "2.6.0" %}

package:
  name: jaraco.envs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jaraco.envs/jaraco.envs-{{ version }}.tar.gz
  sha256: 809195c406640db256ee01eebf4f6a369dd85759d8178c3921704308dd0360f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - path
    - python >=3.8
    - tox
    - virtualenv

test:
  requires:
    - pip
  imports:
    - jaraco.envs
  commands:
    - pip check

about:
  home: https://github.com/jaraco/jaraco.envs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Classes for orchestrating Python (virtual) environments.

extra:
  recipe-maintainers:
    - bollwyvl
