{% set name = "jaraco.envs" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce9527140aa45d50d9a2dc0e6565078b864e41ed6848867a3ddf48da9abbe313

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - tox
    - tox-venv
    - virtualenv
    - path
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - jaraco.envs
  commands:
    - pip check

about:
  home: https://github.com/jaraco/jaraco.envs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Classes for orchestrating Python (virtual) environments.

extra:
  recipe-maintainers:
    - bollwyvl
