{% set name = "jaraco.envs" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92d580d7211b932d35b62dd1866b1dcebab15c56afc1ee655c33230dd52e85ec

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - toml
  run:
    - tox
    - tox-venv
    - virtualenv
    - path
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - jaraco.envs
  commands:
    - pip check

about:
  home: https://github.com/jaraco/jaraco.envs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Classes for orchestrating Python (virtual) environments.

extra:
  recipe-maintainers:
    - bollwyvl
